POST http://localhost:8080/videos
Content-Type: application/json

{
    "title": "Video 005",
    "descricao": "Esse é o Video 005",
    "duracao": 180
}

###

GET http://localhost:8080/videos

###

PUT http://localhost:8080/videos/c504427d-9b67-4080-84f9-051043c43aea
Content-Type: application/json

{
    "title": "Video 007",
    "descicao": "Esse é o Video 007",
    "duracao": 180
}